Document: libsimpleamqpclient
Title: Debian libsimpleamqpclient Manual
Author: <insert document author here>
Abstract: This manual describes what libsimpleamqpclient is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libsimpleamqpclient/libsimpleamqpclient.sgml.gz

Format: postscript
Files: /usr/share/doc/libsimpleamqpclient/libsimpleamqpclient.ps.gz

Format: text
Files: /usr/share/doc/libsimpleamqpclient/libsimpleamqpclient.text.gz

Format: HTML
Index: /usr/share/doc/libsimpleamqpclient/html/index.html
Files: /usr/share/doc/libsimpleamqpclient/html/*.html
